<?php
// $Id$

/**
 * Implementation of hook_schema().
 */
function uc_vat_number_cf_schema() {
  $schema['uc_billing_extend'] = array(
    'description' => 'The base table for Vat Number and Fiscal Code.',
    'fields' => array(
      /*'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'size' => 'small',
        'not null' => TRUE,
        'description' => t('Primary key.'),
      ),*/
      'uid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE, // Defaults to FALSE.
        'description' => t('The user ID.'),
      ),
      'order_id' => array(
        'type' => 'int',        
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => t('The order ID.'),
      ),
      'vat_number' => array(
        'type' => 'varchar',
        'length' => 13,
        'not null' => TRUE,
        'default' => '',
        'description' => t('Always state the purpose of your field.'),
      ),
      'cf' => array(
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
        'default' => '',
        'description' => t('Always state the purpose of your field.'),
      ),
    ),
    'indexes' => array(
      'order_id' => array('order_id'),
      'uid' => array('uid'),
    ),
    'foreign keys' => array(
      'uc_orders' => array(
        'table' => 'uc_orders',
        'columns' => array('order_id' => 'order_id'),
      ),
      'user' => array(
        'table' => 'user',
        'columns' => array('uid' => 'uid'),
      ),
    ),
  );
  return $schema;
}